spring:
  datasource:
    url: jdbc:mysql://mysql:3306/talktalk?characterEncoding=UTF-8&serverTimezone=UTC
    username: talktalk
    password: talktalk
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  h2:
    console:
      enabled: false
logging:
  level:
    org.hibernate.SQL: warn